# TODO: Somehow pull python & tool versions from pyproject.toml?
---
default_stages: [commit, push]
exclude: "^(?:nix/.*|.*\\.nix)$"

default_language_version:
  python: python3.12

fail_fast: false
repos:
  - repo: local
    hooks:
      - id: check-poetry
        name: Poetry check
        description: Validates the structure of the pyproject.toml file
        language: python
        entry: poetry check
        pass_filenames: false
        files: pyproject.toml
        always_run: true
        additional_dependencies: [poetry]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [
          --maxkb=5000
        ]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [
          --allow-multiple-documents
        ]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace
        args: [
          --markdown-linebreak-ext=md
        ]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'exec poetry run mypy "$LOCAL_MODULE_FOLDER" tests'
        language: system
        pass_filenames: false
        types: [python]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        # toml included because I may read from toml data files for tests
        types_or: [python, toml]
